// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7nClSo0f4FUC9Wu38Dc970nNS0X1qvNU',
    appId: '1:811251423906:web:a7784e2716f870658295fb',
    messagingSenderId: '811251423906',
    projectId: 'hospitalityplatform-ca7c9',
    authDomain: 'hospitalityplatform-ca7c9.firebaseapp.com',
    storageBucket: 'hospitalityplatform-ca7c9.firebasestorage.app',
    measurementId: 'G-LTVS952YD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacMHGkxQwUymOkym3uVie5hnO64Lg2oo',
    appId: '1:811251423906:android:7af39bc585e602698295fb',
    messagingSenderId: '811251423906',
    projectId: 'hospitalityplatform-ca7c9',
    storageBucket: 'hospitalityplatform-ca7c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_AnTJP7hJKPw-lVoaSDT_MSNDMoxSRwI',
    appId: '1:811251423906:ios:04cbc82263562ce88295fb',
    messagingSenderId: '811251423906',
    projectId: 'hospitalityplatform-ca7c9',
    storageBucket: 'hospitalityplatform-ca7c9.firebasestorage.app',
    iosClientId: '811251423906-2frchfj8kdtjhg5h71k0t492oqvqbjpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalityplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_AnTJP7hJKPw-lVoaSDT_MSNDMoxSRwI',
    appId: '1:811251423906:ios:04cbc82263562ce88295fb',
    messagingSenderId: '811251423906',
    projectId: 'hospitalityplatform-ca7c9',
    storageBucket: 'hospitalityplatform-ca7c9.firebasestorage.app',
    iosClientId: '811251423906-2frchfj8kdtjhg5h71k0t492oqvqbjpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalityplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7nClSo0f4FUC9Wu38Dc970nNS0X1qvNU',
    appId: '1:811251423906:web:a41fc9310a2133938295fb',
    messagingSenderId: '811251423906',
    projectId: 'hospitalityplatform-ca7c9',
    authDomain: 'hospitalityplatform-ca7c9.firebaseapp.com',
    storageBucket: 'hospitalityplatform-ca7c9.firebasestorage.app',
    measurementId: 'G-17N4WN7X64',
  );
}
